version: '3.3'

services:

   postgres:
      image: postgres:14-alpine

      container_name: postgres
      
      restart: always

      ports:
         - 43:5432
      volumes:
         - ./postgresdata:/var/lib/postgresql/data
      env_file:
         - .env.postgres

   web:
      user: "${UID}:${GID}"
      
      restart: always

      image: ivanduque0/hostlocal-django:V0.1

      container_name: web
      
      command: gunicorn tesisweb.wsgi:application --bind 0.0.0.0:8000
      volumes:
         - ./tesisweb/web:/home/app/web/web
         - ./tesisweb/tesisweb:/home/app/web/tesisweb
      #ports:
         #- 8282:8000
      expose:
         - 8000
      env_file:
         - .env.manager
      depends_on:
         - postgres 
      privileged: true
      
         
   nginx:
      image: ivanduque0/hostlocal-nginx:V0.1

      restart: always

      container_name: nginx

      ports:
         - 1010:80
      depends_on:
         - web

   dbmaker:
   
      image: ivanduque0/dbmakermanager:V0.3
      
      volumes:
         - ./dbmaker:/app
         
      command: python3 codigo.py
         
      env_file:
         - .env.manager
         
      depends_on:
         - postgres

   dbmanagerall:
   
      image: ivanduque0/dbmakermanager:V0.3

      container_name: dbmanagerall
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./allmanager:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres
   
   ping:
   
      image: ivanduque0/dbmakermanager:V0.3

      container_name: ping
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./pingdispositivos:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres
   
   
      
   
